name: PHP Composer

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest
    
    - name: Run Tests
      run: ./vendor/bin/phpunit --configuration phpunit.xml
    
    - name: Validate class documentation
      run: ./vendor/bin/lazydoctor -c composer.json -pfo --validate-only >/dev/null
    
    - name: Validate checkStyle script
      run: /usr/bin/env php devtools/checkStyle.php x

    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
